############################################################
## mybatis mapper 配置
#############################################################
# 通用 Mapper 配置
mapper:
  mappers: top.taka.my.mapper.MyMapper
  not-empty: false # 在进行数据库操作的时候，判断表达式 userName != null 时，是否追加判断 userName != ''
  identity: MYSQL